<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>QfStudio.Godette.ReactiveUI</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>QfStudio.Godette.ReactiveUI</PackageId>
    <PackageVersion>1.2-beta5</PackageVersion>
    <Authors>lightyears1998</Authors>
    <Description>ReactiveUI MVVM framework integration for Godot Engine</Description>
    <PackageTags>godot4;mvvm;reactiveui</PackageTags>
    <PackageProjectUrl>https://github.com/qfstudio/QfStudio.Godette.ReactiveUI</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/qfstudio/QfStudio.Godette.ReactiveUI.git</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <!-- CS1591: Missing XML comment for public members -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GodotSharp" Version="4.1" />
    <PackageReference Include="ReactiveUI" Version="23.2.28" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QfStudio.Godette.ReactiveUI.SourceGenerators\QfStudio.Godette.ReactiveUI.SourceGenerators.csproj"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <Target Name="PackAnalyzer" BeforeTargets="_GetPackageFiles">
    <MSBuild Projects="..\QfStudio.Godette.ReactiveUI.SourceGenerators\QfStudio.Godette.ReactiveUI.SourceGenerators.csproj"
             Targets="GetTargetPath">
      <Output TaskParameter="TargetOutputs" ItemName="_AnalyzerPath" />
    </MSBuild>
    <ItemGroup>
      <None Include="@(_AnalyzerPath)" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    </ItemGroup>
  </Target>
</Project>
